[package]
name = "rillrate-system-protocol"
version = "0.2.0"
edition = "2018"
description = "RillRate agent for system monitoring. Protocol."
license = "Apache-2.0"

[dependencies]
rill-protocol = "0.30.0-alpha.4"
serde = "1.0.126"
vectorize = "0.1.0"
